
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 17 17:26:42 CEST 2018
//----------------------------------------------------

package compiler;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int CLOSE_BRACKET = 13;
  public static final int USE_INTERFACE = 15;
  public static final int OPEN_CURLY = 10;
  public static final int COMPONENT = 4;
  public static final int COMPLEXCOMPONENT = 3;
  public static final int NAME = 17;
  public static final int T_MODEL = 2;
  public static final int OPEN_BRACKET = 12;
  public static final int CONTAINS = 5;
  public static final int REALIZE = 9;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int INTERFACE = 7;
  public static final int CLOSE_CURLY = 11;
  public static final int USE = 8;
  public static final int O_PORT = 6;
  public static final int REALIZE_INTERFACE = 16;
}

